apiVersion: v1
kind: Service
metadata:
  name: nextjs-vllm-ui
  labels:
    app: nextjs-vllm-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: nextjs-vllm-ui
